# Generated by Django 5.2.6 on 2025-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tamil", models.PositiveIntegerField()),
                ("english", models.PositiveIntegerField()),
                ("maths", models.PositiveIntegerField()),
                ("science", models.PositiveIntegerField()),
                ("social", models.PositiveIntegerField()),
                ("grade", models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
